### ISSUE TITLE
生态邀请

### ISSUE THREAD

**Issue by yt605155624** [kslz/PSTTS-local#1]
- 可以新增一个 requirements.txt 里面写上 paddlespeech 这样就能在 PaddleSpeech 仓库右侧 **Used by** 里面看到你这个仓库
- 可以给 PaddleSpeech repo 提交一个 readme 的修改，参考 https://github.com/PaddlePaddle/PaddleSpeech/pull/2688/files

**Comment by kslz** [comment]
1加了 2的话等我以后写出超厉害的代码再加吧 😄
