### ISSUE TITLE
请问这个项目是【关于训练一个自己的TTS模型】的延伸吗

### ISSUE THREAD

**Issue by makeukus** [kslz/PSTTS-local#2]
请问这个项目是【关于训练一个自己的TTS模型】的延伸吗
https://github.com/PaddlePaddle/PaddleSpeech/discussions/1842

**Comment by kslz** [comment]
可以是，就是简单的封装了一下。不过写的很差劲，还是建议不要用

**Comment by makeukus** [comment]
不能够，感觉大哥你这方面还是挺厉害的。有个问题请教下大哥，【关于训练一个自己的TTS模型】和https://aistudio.baidu.com/aistudio/projectdetail/5003396 这个是一回事儿吗，有手就行这个我能够Run，但是最终效果不太好。所以我想尝试一下 全新模型训练

**Comment by kslz** [comment]
我建议直接问开发，或者试试VITS 它的效果也很好

**Comment by makeukus** [comment]
> 我建议直接问开发，或者试试VITS 它的效果也很好

谢谢，已经尝试VITS，确实感觉比fastspeech2这个要好
